server:
  port: 8888
  servlet:
    session:
      timeout: 30m 
#  servlet:
#    context-path: /test


spring:
  datasource:
    url: "jdbc:mysql://100.126.177.112:3306/ekomart"
    username: username
    password: password
  servlet:
   multipart:
     enabled: true
     max-file-size: 5MB
     max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm

  mail:
    host: smtp.gmail.com
    port: 587
    username: trantiendat1679@gmail.com
    password: ckclltbdkatufiho
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            protocols: TLSv1.2
storage:
  location: D:\\upload
