server:
  port: 8888
#  servlet:
#    context-path: /test


spring:
  datasource:
<<<<<<< HEAD
#    url: "jdbc:mysql://26.168.186.68:3306/ekomart"
#    username: username
#    password: password

    #db cua tiendat
    url: "jdbc:mysql://localhost:3306/springb3_security6"
    username: security_su
    password: 1234567@a$
=======
    url: "jdbc:mysql://127.0.0.1:3306/ekomart"
    username: root
    password: root
>>>>>>> mun
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: trantiendat1679@gmail.com
    password: ckclltbdkatufiho
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            protocols: TLSv1.2